// <auto-generated />
using System;
using HapagPortal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HapagPortal.DatabaseMigrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512145938_AddDemoSeedData")]
    partial class AddDemoSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HapagPortal.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EntityName");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.BLContainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillOfLadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContainerType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SealNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillOfLadingId");

                    b.HasIndex("ContainerNumber");

                    b.ToTable("BLContainers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0008-0008-0008-000000000001"),
                            BillOfLadingId = new Guid("11111111-0007-0007-0007-000000000001"),
                            ContainerNumber = "HLXU1234567",
                            ContainerType = "40HC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            SealNumber = "SL-001234",
                            Status = "Discharged",
                            Weight = 24500m
                        },
                        new
                        {
                            Id = new Guid("22222222-0008-0008-0008-000000000002"),
                            BillOfLadingId = new Guid("11111111-0007-0007-0007-000000000001"),
                            ContainerNumber = "HLXU7654321",
                            ContainerType = "20DV",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            SealNumber = "SL-005678",
                            Status = "Discharged",
                            Weight = 18200m
                        },
                        new
                        {
                            Id = new Guid("22222222-0008-0008-0008-000000000003"),
                            BillOfLadingId = new Guid("11111111-0007-0007-0007-000000000002"),
                            ContainerNumber = "HLXU9876543",
                            ContainerType = "40HC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            SealNumber = "SL-009012",
                            Status = "OnBoard",
                            Weight = 22100m
                        },
                        new
                        {
                            Id = new Guid("22222222-0008-0008-0008-000000000004"),
                            BillOfLadingId = new Guid("11111111-0007-0007-0007-000000000002"),
                            ContainerNumber = "HLXU1112233",
                            ContainerType = "40RF",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            SealNumber = "SL-003456",
                            Status = "OnBoard",
                            Weight = 19800m
                        },
                        new
                        {
                            Id = new Guid("22222222-0008-0008-0008-000000000005"),
                            BillOfLadingId = new Guid("11111111-0007-0007-0007-000000000003"),
                            ContainerNumber = "HLXU4455667",
                            ContainerType = "40OT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            SealNumber = "SL-007890",
                            Status = "Delivered",
                            Weight = 31500m
                        });
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.BillOfLading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BLNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Consignee")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ETA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ETD")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FreightAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FreightCurrency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NotifyParty")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PortOfDischarge")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PortOfLoading")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShipmentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Shipper")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Vessel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Voyage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BLNumber")
                        .IsUnique();

                    b.HasIndex("ClientId");

                    b.ToTable("BillsOfLading", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0007-0007-0007-000000000001"),
                            BLNumber = "HLCUVAL250100123",
                            ClientId = new Guid("c3d4e5f6-0003-0003-0003-000000000010"),
                            Consignee = "Importadora Demo SpA",
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            ETA = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ETD = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FreightAmount = 3500m,
                            FreightCurrency = "USD",
                            PortOfDischarge = "San Antonio (CLSAI)",
                            PortOfLoading = "Shanghai (CNSHA)",
                            ShipmentType = "Import",
                            Shipper = "Shanghai Electronics Co. Ltd",
                            Status = "Arrived",
                            Vessel = "Hamburg Express",
                            Voyage = "025E"
                        },
                        new
                        {
                            Id = new Guid("11111111-0007-0007-0007-000000000002"),
                            BLNumber = "HLCUVAL250200456",
                            ClientId = new Guid("c3d4e5f6-0003-0003-0003-000000000010"),
                            Consignee = "Importadora Demo SpA",
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            ETA = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ETD = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FreightAmount = 5200m,
                            FreightCurrency = "USD",
                            PortOfDischarge = "Valparaíso (CLVAP)",
                            PortOfLoading = "Busan (KRPUS)",
                            ShipmentType = "Import",
                            Shipper = "Korea Auto Parts Inc.",
                            Status = "InTransit",
                            Vessel = "Berlin Express",
                            Voyage = "031W"
                        },
                        new
                        {
                            Id = new Guid("11111111-0007-0007-0007-000000000003"),
                            BLNumber = "HLCUVAL250300789",
                            ClientId = new Guid("c3d4e5f6-0003-0003-0003-000000000001"),
                            Consignee = "Hapag-Lloyd Administrador",
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            ETA = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ETD = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FreightAmount = 8750m,
                            FreightCurrency = "USD",
                            PortOfDischarge = "San Antonio (CLSAI)",
                            PortOfLoading = "Rotterdam (NLRTM)",
                            ShipmentType = "Import",
                            Shipper = "European Machinery GmbH",
                            Status = "Delivered",
                            Vessel = "Colombo Express",
                            Voyage = "018E"
                        });
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AgentCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxIdType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TaxId", "Country")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0003-0003-000000000001"),
                            ClientType = "Internal",
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Email = "admin@hapag-lloyd.cl",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Name = "Hapag-Lloyd Administrador",
                            Phone = "+56 2 2630 1700",
                            TaxId = "99999999-K",
                            TaxIdType = "RUT"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-0003-0003-0003-000000000010"),
                            ClientType = "Client",
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Email = "demo@importadorademo.cl",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            Name = "Importadora Demo SpA",
                            Phone = "+56 2 2345 6789",
                            TaxId = "76.123.456-7",
                            TaxIdType = "RUT"
                        });
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.CreditClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreditStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "Country")
                        .IsUnique();

                    b.ToTable("CreditClients", (string)null);
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("ExchangeRateToUSD")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            Code = "CLP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            ExchangeRateToUSD = 950m,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Peso Chileno",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            Code = "BOB",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            ExchangeRateToUSD = 6.91m,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Boliviano",
                            Symbol = "Bs"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            Code = "USD",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            ExchangeRateToUSD = 1m,
                            LastUpdated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "US Dollar",
                            Symbol = "$"
                        });
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.DemurrageCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillOfLadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("DailyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("DemurrageDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExemptReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FreeDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsExempt")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillOfLadingId");

                    b.ToTable("DemurrageCharges", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-000a-000a-000a-000000000001"),
                            BillOfLadingId = new Guid("11111111-0007-0007-0007-000000000001"),
                            ContainerNumber = "HLXU1234567",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Currency = "CLP",
                            DailyRate = 45000m,
                            DemurrageDays = 5,
                            EndDate = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            FreeDays = 7,
                            IsExempt = false,
                            StartDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            TotalAmount = 225000m
                        },
                        new
                        {
                            Id = new Guid("44444444-000a-000a-000a-000000000002"),
                            BillOfLadingId = new Guid("11111111-0007-0007-0007-000000000001"),
                            ContainerNumber = "HLXU7654321",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Currency = "CLP",
                            DailyRate = 35000m,
                            DemurrageDays = 3,
                            EndDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FreeDays = 7,
                            IsExempt = false,
                            StartDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            TotalAmount = 105000m
                        });
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.DemurrageExemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TaxId", "Country")
                        .IsUnique();

                    b.ToTable("DemurrageExemptions", (string)null);
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.FAQ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Country", "Category");

                    b.ToTable("FAQs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6a7b8c9-0006-0006-0006-000000000001"),
                            Answer = "Ingrese al módulo 'Bills of Lading', escriba su número de BL en el buscador y presione buscar. Verá el detalle completo incluyendo contenedores, cargos locales y demurrage.",
                            Category = "SHIPPING",
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Question = "¿Cómo puedo consultar el estado de mi BL?",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-0006-0006-0006-000000000002"),
                            Answer = "En Chile puede pagar con Tarjeta de Crédito, Tarjeta de Débito, Transferencia Bancaria y WebPay. Todos los pagos electrónicos se procesan en tiempo real.",
                            Category = "PAYMENTS",
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Question = "¿Qué métodos de pago están disponibles en Chile?",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-0006-0006-0006-000000000003"),
                            Answer = "Vaya al módulo 'Cambio de Almacén', ingrese el número de BL, el contenedor, el almacén actual y el almacén destino. La solicitud será procesada y recibirá confirmación por correo.",
                            Category = "SHIPPING",
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Question = "¿Cómo solicito un cambio de almacén?",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-0006-0006-0006-000000000004"),
                            Answer = "La tasa de IVA vigente en Chile es del 19%. Se aplica automáticamente sobre los cargos locales y servicios facturables.",
                            Category = "PAYMENTS",
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Question = "¿Cuál es la tasa de IVA aplicada en Chile?",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-0006-0006-0006-000000000005"),
                            Answer = "Una vez confirmado el pago, vaya al detalle del pago y presione 'Generar Recibo'. El recibo se genera automáticamente en formato PDF con todos los datos fiscales.",
                            Category = "DOCUMENTATION",
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Question = "¿Cómo genero un recibo de pago?",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-0006-0006-0006-000000000011"),
                            Answer = "Ingrese al módulo 'Bills of Lading' y busque por número de BL. Verá el estado de su carga incluyendo el puerto de ingreso (Arica, Iquique o Antofagasta) y los cargos asociados.",
                            Category = "SHIPPING",
                            Country = "BO",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Question = "¿Cómo puedo consultar el estado de mi BL en Bolivia?",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-0006-0006-0006-000000000012"),
                            Answer = "En Bolivia puede pagar mediante Transferencia Bancaria, Efectivo y Cheque. Los pagos en efectivo deben realizarse en oficinas autorizadas.",
                            Category = "PAYMENTS",
                            Country = "BO",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Question = "¿Qué métodos de pago están disponibles en Bolivia?",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-0006-0006-0006-000000000013"),
                            Answer = "La tasa de IVA vigente en Bolivia es del 13%. Se aplica automáticamente sobre los cargos locales y servicios facturables. Los montos se manejan en Bolivianos (BOB).",
                            Category = "PAYMENTS",
                            Country = "BO",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Question = "¿Cuál es la tasa de IVA aplicada en Bolivia?",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-0006-0006-0006-000000000014"),
                            Answer = "El NIT (Número de Identificación Tributaria) es el identificador fiscal en Bolivia. Es obligatorio para el registro en el portal y para la emisión de documentos fiscales.",
                            Category = "GENERAL",
                            Country = "BO",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Question = "¿Qué es el NIT y por qué lo necesito?",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-0006-0006-0006-000000000015"),
                            Answer = "El demurrage se calcula desde la fecha de descarga en el puerto chileno. Los días libres y tarifas diarias dependen del tipo de contenedor y acuerdos comerciales. Puede solicitar exenciones a través del módulo de Demurrage.",
                            Category = "DEMURRAGE",
                            Country = "BO",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Question = "¿Cómo funciona el demurrage para carga en tránsito a Bolivia?",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-0006-0006-0006-000000000021"),
                            Answer = "Haga clic en 'Registrarse', seleccione su país (Chile o Bolivia), ingrese los datos de su empresa (RUT/NIT, nombre, correo) y cree una contraseña. Recibirá un correo de confirmación.",
                            Category = "GENERAL",
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Question = "¿Cómo registro mi empresa en el portal?",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-0006-0006-0006-000000000022"),
                            Answer = "En la pantalla de login, haga clic en '¿Olvidó su contraseña?'. Ingrese su correo electrónico y recibirá un enlace para restablecer su contraseña.",
                            Category = "GENERAL",
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Question = "¿Olvidé mi contraseña, cómo la recupero?",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-0006-0006-0006-000000000023"),
                            Answer = "Puede contactarnos al correo clservice@hapag-lloyd.com o llamar al +56 2 2630 1700 (Chile) / +591 2 211 0700 (Bolivia) en horario de oficina de lunes a viernes.",
                            Category = "GENERAL",
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            IsActive = true,
                            Question = "¿Cómo contacto a soporte técnico?",
                            SortOrder = 12
                        });
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.LocalCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BillOfLadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChargeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillOfLadingId");

                    b.ToTable("LocalCharges", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0009-0009-0009-000000000001"),
                            Amount = 185000m,
                            BillOfLadingId = new Guid("11111111-0007-0007-0007-000000000001"),
                            ChargeType = "THC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Currency = "CLP",
                            Description = "Terminal Handling Charge - 40HC",
                            IsTaxable = true,
                            Status = "Pending",
                            TaxAmount = 35150m,
                            TaxRate = 19m,
                            TotalAmount = 220150m
                        },
                        new
                        {
                            Id = new Guid("33333333-0009-0009-0009-000000000002"),
                            Amount = 45000m,
                            BillOfLadingId = new Guid("11111111-0007-0007-0007-000000000001"),
                            ChargeType = "BL_FEE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Currency = "CLP",
                            Description = "BL Documentation Fee",
                            IsTaxable = true,
                            Status = "Pending",
                            TaxAmount = 8550m,
                            TaxRate = 19m,
                            TotalAmount = 53550m
                        },
                        new
                        {
                            Id = new Guid("33333333-0009-0009-0009-000000000003"),
                            Amount = 25000m,
                            BillOfLadingId = new Guid("11111111-0007-0007-0007-000000000001"),
                            ChargeType = "ISPS",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Currency = "CLP",
                            Description = "ISPS Security Surcharge",
                            IsTaxable = true,
                            Status = "Pending",
                            TaxAmount = 4750m,
                            TaxRate = 19m,
                            TotalAmount = 29750m
                        },
                        new
                        {
                            Id = new Guid("33333333-0009-0009-0009-000000000004"),
                            Amount = 185000m,
                            BillOfLadingId = new Guid("11111111-0007-0007-0007-000000000002"),
                            ChargeType = "THC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Currency = "CLP",
                            Description = "Terminal Handling Charge - 40HC",
                            IsTaxable = true,
                            Status = "Pending",
                            TaxAmount = 35150m,
                            TaxRate = 19m,
                            TotalAmount = 220150m
                        },
                        new
                        {
                            Id = new Guid("33333333-0009-0009-0009-000000000005"),
                            Amount = 295000m,
                            BillOfLadingId = new Guid("11111111-0007-0007-0007-000000000002"),
                            ChargeType = "THC_RF",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Currency = "CLP",
                            Description = "Terminal Handling Charge - 40RF Reefer",
                            IsTaxable = true,
                            Status = "Pending",
                            TaxAmount = 56050m,
                            TaxRate = 19m,
                            TotalAmount = 351050m
                        },
                        new
                        {
                            Id = new Guid("33333333-0009-0009-0009-000000000006"),
                            Amount = 210000m,
                            BillOfLadingId = new Guid("11111111-0007-0007-0007-000000000003"),
                            ChargeType = "THC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Currency = "CLP",
                            Description = "Terminal Handling Charge - 40OT",
                            IsTaxable = true,
                            Status = "Paid",
                            TaxAmount = 39900m,
                            TaxRate = 19m,
                            TotalAmount = 249900m
                        });
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BillOfLadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DepositProofUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("ExchangeRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillOfLadingId");

                    b.HasIndex("ClientId");

                    b.HasIndex("PaymentNumber")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.PaymentDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ConceptType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentDetails", (string)null);
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillOfLadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("BillOfLadingId");

                    b.HasIndex("ClientId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("ServiceOrders", (string)null);
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.TaxConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.HasKey("Id");

                    b.HasIndex("Country", "ServiceType")
                        .IsUnique();

                    b.ToTable("TaxConfigurations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2c3d4e5-0002-0002-0002-000000000001"),
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ServiceType = "General",
                            TaxName = "IVA",
                            TaxRate = 19m
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-0002-0002-0002-000000000002"),
                            Country = "BO",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            ServiceType = "General",
                            TaxName = "IVA",
                            TaxRate = 13m
                        });
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0004-0004-000000000001"),
                            ClientId = new Guid("c3d4e5f6-0003-0003-0003-000000000001"),
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Email = "admin@hapag-lloyd.cl",
                            IsActive = true,
                            PasswordHash = "$2a$12$cSxUVEI1bQ2CYNR.7dqfz.FTbfVBKY0xLO6/rDbvCvQ54ildbUKca",
                            UserType = "Admin",
                            Username = "admin@hapag-lloyd.cl"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-0004-0004-0004-000000000010"),
                            ClientId = new Guid("c3d4e5f6-0003-0003-0003-000000000010"),
                            Country = "CL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "SYSTEM",
                            Email = "demo@importadorademo.cl",
                            IsActive = true,
                            PasswordHash = "$2a$12$cSxUVEI1bQ2CYNR.7dqfz.FTbfVBKY0xLO6/rDbvCvQ54ildbUKca",
                            UserType = "Client",
                            Username = "demo@importadorademo.cl"
                        });
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RoleName")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5f6a7b8-0005-0005-0005-000000000001"),
                            RoleName = "Admin",
                            UserId = new Guid("d4e5f6a7-0004-0004-0004-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-0005-0005-0005-000000000010"),
                            RoleName = "User",
                            UserId = new Guid("d4e5f6a7-0004-0004-0004-000000000010")
                        });
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.WarehouseChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BillOfLadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FromWarehouse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ToWarehouse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BillOfLadingId");

                    b.ToTable("WarehouseChanges", (string)null);
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.BLContainer", b =>
                {
                    b.HasOne("HapagPortal.Domain.Entities.BillOfLading", "BillOfLading")
                        .WithMany("Containers")
                        .HasForeignKey("BillOfLadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillOfLading");
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.BillOfLading", b =>
                {
                    b.HasOne("HapagPortal.Domain.Entities.Client", "Client")
                        .WithMany("BillsOfLading")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.CreditClient", b =>
                {
                    b.HasOne("HapagPortal.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.DemurrageCharge", b =>
                {
                    b.HasOne("HapagPortal.Domain.Entities.BillOfLading", "BillOfLading")
                        .WithMany("DemurrageCharges")
                        .HasForeignKey("BillOfLadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillOfLading");
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.LocalCharge", b =>
                {
                    b.HasOne("HapagPortal.Domain.Entities.BillOfLading", "BillOfLading")
                        .WithMany("LocalCharges")
                        .HasForeignKey("BillOfLadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillOfLading");
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.Payment", b =>
                {
                    b.HasOne("HapagPortal.Domain.Entities.BillOfLading", "BillOfLading")
                        .WithMany("Payments")
                        .HasForeignKey("BillOfLadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HapagPortal.Domain.Entities.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillOfLading");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.PaymentDetail", b =>
                {
                    b.HasOne("HapagPortal.Domain.Entities.Payment", "Payment")
                        .WithMany("Details")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.ServiceOrder", b =>
                {
                    b.HasOne("HapagPortal.Domain.Entities.BillOfLading", "BillOfLading")
                        .WithMany()
                        .HasForeignKey("BillOfLadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HapagPortal.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillOfLading");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.User", b =>
                {
                    b.HasOne("HapagPortal.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("HapagPortal.Domain.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.WarehouseChange", b =>
                {
                    b.HasOne("HapagPortal.Domain.Entities.BillOfLading", "BillOfLading")
                        .WithMany()
                        .HasForeignKey("BillOfLadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillOfLading");
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.BillOfLading", b =>
                {
                    b.Navigation("Containers");

                    b.Navigation("DemurrageCharges");

                    b.Navigation("LocalCharges");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.Client", b =>
                {
                    b.Navigation("BillsOfLading");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.Payment", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("HapagPortal.Domain.Entities.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
